export { default as Home } from './Home'
export { default as Form } from './Form'
export { default as Files } from './Files'
export { default as Share } from './Share'
export { default as Help } from './Help'
export { default as Setting } from './Setting'
export { default as Sponsor } from './Sponsor'
export { default as Animate } from './Animate'
